# DEPLOY_TARGET: openshift
# BUILD_ARCH: arm64
FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/python-311
WORKDIR /opt/app-root/src
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000"]
